#!/usr/bin/env python3
"""Generate 300 additional unique shop products with real Indian FMCG names."""

from __future__ import annotations

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CATALOG = SCRIPT_DIR.parents[1] / "mobile" / "src" / "data" / "shopCatalog.json"
OUT = SCRIPT_DIR / "shop_extra_seed.py"

# (brand, name, category, subCategory, unit, price, mrp)
TEMPLATES: list[tuple] = [
    ("Amul", "Lite Milk", "Dairy & Breakfast", "Milk", "500 ml", 52, 55),
    ("Amul", "Lite Milk", "Dairy & Breakfast", "Milk", "1 L", 98, 105),
    ("Amul", "Chocolate Milk", "Dairy & Breakfast", "Milk", "200 ml", 25, 28),
    ("Amul", "Kool Koko Milkshake", "Dairy & Breakfast", "Milk", "180 ml", 22, 25),
    ("Amul", "Masti Spiced Buttermilk", "Dairy & Breakfast", "Buttermilk", "200 ml", 15, 18),
    ("Amul", "Ice Cream Vanilla Magic", "Frozen Food", "Ice Cream", "750 ml", 165, 185),
    ("Amul", "Ice Cream Rajbhog", "Frozen Food", "Ice Cream", "1 L", 195, 220),
    ("Amul", "Ice Cream Cassata Slice", "Frozen Food", "Ice Cream", "125 ml", 35, 40),
    ("Mother Dairy", "Fit Life Toned Milk", "Dairy & Breakfast", "Milk", "1 L", 68, 72),
    ("Mother Dairy", "Diet Yogurt Blueberry", "Dairy & Breakfast", "Yogurt", "85 g", 28, 32),
    ("Mother Dairy", "Diet Yogurt Mango", "Dairy & Breakfast", "Yogurt", "85 g", 28, 32),
    ("Mother Dairy", "Paneer Classic", "Dairy & Breakfast", "Paneer", "200 g", 92, 99),
    ("Mother Dairy", "Paneer Classic", "Dairy & Breakfast", "Paneer", "500 g", 215, 235),
    ("Britannia", "Treat Croissant", "Bakery", "Croissant", "47 g", 25, 28),
    ("Britannia", "Cake Gobbles Fruity Fun", "Bakery", "Cake", "110 g", 35, 40),
    ("Britannia", "Cake Gobbles Choco Chill", "Bakery", "Cake", "110 g", 35, 40),
    ("Britannia", "Winkin Cow Thick Shake", "Beverages", "Milk Shake", "180 ml", 30, 35),
    ("Britannia", "NutriChoice 5 Grain", "Dairy & Breakfast", "Biscuits", "150 g", 45, 50),
    ("Britannia", "NutriChoice Essentials", "Dairy & Breakfast", "Biscuits", "75 g", 28, 32),
    ("Nestle", "Milo Active Go", "Beverages", "Health Drink", "400 g", 245, 265),
    ("Nestle", "Cerelac Wheat Apple Cherry", "Baby Care", "Baby Food", "300 g", 265, 285),
    ("Nestle", "Cerelac Rice Vegetables", "Baby Care", "Baby Food", "300 g", 255, 275),
    ("Nestle", "Everyday Shahi Ghee", "Dairy & Breakfast", "Ghee", "200 ml", 145, 155),
    ("Nestle", "Maggi Pazzta Cheese Macaroni", "Staples & Grains", "Pasta", "70 g", 28, 32),
    ("Nestle", "Maggi Pazzta Masala Penne", "Staples & Grains", "Pasta", "70 g", 28, 32),
    ("Cadbury", "Oreo Choco Creme", "Snacks & Munchies", "Biscuits", "120 g", 45, 50),
    ("Cadbury", "Bournville Fruit & Nut", "Snacks & Munchies", "Chocolate", "80 g", 125, 135),
    ("Cadbury", "Celebrations Assorted", "Snacks & Munchies", "Chocolate", "135 g", 175, 195),
    ("Cadbury", "Silk Bubbly", "Snacks & Munchies", "Chocolate", "50 g", 75, 85),
    ("Haldiram's", "Navratan Mix", "Snacks & Munchies", "Namkeen", "200 g", 55, 60),
    ("Haldiram's", "Lite Mixture", "Snacks & Munchies", "Namkeen", "200 g", 50, 55),
    ("Haldiram's", "Soan Papdi", "Snacks & Munchies", "Sweets", "250 g", 85, 95),
    ("Haldiram's", "Gulab Jamun Tin", "Snacks & Munchies", "Sweets", "1 kg", 195, 215),
    ("Haldiram's", "Rasgulla Tin", "Snacks & Munchies", "Sweets", "1 kg", 175, 195),
    ("Lay's", "American Style Cream & Onion", "Snacks & Munchies", "Chips", "52 g", 20, 20),
    ("Lay's", "Wafer Style Salted", "Snacks & Munchies", "Chips", "48 g", 20, 20),
    ("Lay's", "Wafer Style Chile Limon", "Snacks & Munchies", "Chips", "48 g", 20, 20),
    ("Kurkure", "Puffcorn Yummy Cheese", "Snacks & Munchies", "Snacks", "60 g", 20, 20),
    ("Kurkure", "Solid Masti Masala", "Snacks & Munchies", "Snacks", "90 g", 20, 20),
    ("Bingo", "Tedhe Medhe Masala Tadka", "Snacks & Munchies", "Snacks", "85 g", 20, 20),
    ("Bingo", "Hashtags Spicy Korean Style", "Snacks & Munchies", "Snacks", "66 g", 20, 20),
    ("Parle", "Hide & Seek Caffe Mocha", "Snacks & Munchies", "Biscuits", "120 g", 45, 50),
    ("Parle", "Melody Toffee", "Snacks & Munchies", "Toffee", "391 g", 95, 105),
    ("Sunfeast", "Mom's Magic Rich Cashew Almond", "Snacks & Munchies", "Biscuits", "200 g", 55, 60),
    ("Sunfeast", "Bounce Orange", "Snacks & Munchies", "Biscuits", "300 g", 45, 50),
    ("Sunfeast", "Yippee Mood Masala Noodles", "Staples & Grains", "Noodles", "65 g", 14, 14),
    ("Sunfeast", "Yippee Magic Masala Noodles", "Staples & Grains", "Noodles", "280 g", 55, 60),
    ("Maggi", "Nutri-licious Masala Veg Atta Noodles", "Staples & Grains", "Noodles", "72.5 g", 18, 20),
    ("Maggi", "Hot Heads Carolina Reaper", "Staples & Grains", "Noodles", "70 g", 16, 18),
    ("Knorr", "International Thai Green Curry", "Staples & Grains", "Soup", "46 g", 55, 60),
    ("Knorr", "International Mexican Tomato Corn", "Staples & Grains", "Soup", "52 g", 55, 60),
    ("Kissan", "No Onion No Garlic Tomato Sauce", "Staples & Grains", "Sauces", "500 g", 85, 95),
    ("Kissan", "Fresh Tomato Ketchup", "Staples & Grains", "Sauces", "950 g", 125, 140),
    ("Heinz", "Tomato Ketchup No Added Sugar", "Staples & Grains", "Sauces", "570 g", 145, 160),
    ("Ching's", "Hakka Noodles", "Staples & Grains", "Noodles", "150 g", 35, 40),
    ("Ching's", "Schezwan Instant Noodles", "Staples & Grains", "Noodles", "60 g", 15, 18),
    ("Ching's", "Green Chilli Sauce", "Staples & Grains", "Sauces", "190 g", 45, 50),
    ("Fortune", "Kachi Ghani Mustard Oil", "Staples & Grains", "Oil", "1 L", 155, 170),
    ("Fortune", "Rice Bran Health Oil", "Staples & Grains", "Oil", "1 L", 165, 180),
    ("Fortune", "Soya Health Oil", "Staples & Grains", "Oil", "1 L", 145, 160),
    ("Saffola", "Active Oil", "Staples & Grains", "Oil", "1 L", 175, 190),
    ("Saffola", "Total Heart Pro Oil", "Staples & Grains", "Oil", "1 L", 195, 215),
    ("Aashirvaad", "Atta with Multigrains", "Staples & Grains", "Atta", "5 kg", 315, 340),
    ("Aashirvaad", "Atta Select Sharbati", "Staples & Grains", "Atta", "10 kg", 525, 565),
    ("India Gate", "Basmati Rice Dubar", "Staples & Grains", "Rice", "5 kg", 525, 565),
    ("India Gate", "Basmati Rice Mogra", "Staples & Grains", "Rice", "5 kg", 385, 415),
    ("Daawat", "Devaaya Basmati Rice", "Staples & Grains", "Rice", "1 kg", 145, 160),
    ("Tata Sampann", "Moong Dal", "Staples & Grains", "Dal", "500 g", 75, 82),
    ("Tata Sampann", "Urad Dal", "Staples & Grains", "Dal", "500 g", 85, 92),
    ("Tata Sampann", "Masoor Dal", "Staples & Grains", "Dal", "500 g", 72, 78),
    ("Tata Sampann", "Poha Thick", "Staples & Grains", "Poha", "500 g", 45, 50),
    ("MDH", "Dal Makhani Masala", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("MDH", "Kitchen King Masala", "Staples & Grains", "Spices", "100 g", 72, 78),
    ("Everest", "Pav Bhaji Masala", "Staples & Grains", "Spices", "100 g", 68, 75),
    ("Everest", "Sambhar Masala", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Catch", "Sprinkler Black Salt", "Staples & Grains", "Spices", "200 g", 35, 40),
    ("Catch", "Red Chilli Powder", "Staples & Grains", "Spices", "200 g", 85, 92),
    ("Dabur", "Real Activ Mixed Fruit Juice", "Beverages", "Juice", "1 L", 125, 135),
    ("Dabur", "Real Activ Orange Juice", "Beverages", "Juice", "1 L", 115, 125),
    ("Real", "Activ Mixed Fruit", "Beverages", "Juice", "1 L", 120, 130),
    ("Real", "Fruit Power Litchi", "Beverages", "Juice", "1 L", 110, 120),
    ("Real", "Fruit Power Guava", "Beverages", "Juice", "1 L", 110, 120),
    ("Tropicana", "Delight Mixed Fruit", "Beverages", "Juice", "1 L", 135, 145),
    ("Tropicana", "Delight Orange", "Beverages", "Juice", "1 L", 125, 135),
    ("Paper Boat", "Aam Panna", "Beverages", "Juice", "250 ml", 35, 40),
    ("Paper Boat", "Jaljeera", "Beverages", "Juice", "250 ml", 35, 40),
    ("Paper Boat", "Swing Zesty Pomegranate", "Beverages", "Juice", "600 ml", 55, 60),
    ("Bisleri", "Vedica Himalayan Water", "Beverages", "Water", "1 L", 35, 40),
    ("Bisleri", "Packaged Water", "Beverages", "Water", "2 L", 35, 40),
    ("Kinley", "Packaged Water", "Beverages", "Water", "1 L", 18, 20),
    ("Aquafina", "Packaged Water", "Beverages", "Water", "1 L", 18, 20),
    ("Coca-Cola", "Zero Sugar", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Pepsi", "Black Zero Sugar", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Sprite", "Zero Sugar", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Thums Up", "Charged No Sugar", "Beverages", "Soft Drinks", "250 ml", 20, 20),
    ("Red Bull", "Sugar Free", "Beverages", "Energy", "250 ml", 125, 135),
    ("Sting", "Energy Drink", "Beverages", "Energy", "250 ml", 20, 20),
    ("Monster", "Energy Drink", "Beverages", "Energy", "350 ml", 95, 105),
    ("Bru", "Gold Freeze Dried Coffee", "Beverages", "Coffee", "100 g", 325, 350),
    ("Nescafe", "Gold Coffee", "Beverages", "Coffee", "50 g", 245, 265),
    ("Tata Tea", "Premium Tea", "Beverages", "Tea", "500 g", 285, 310),
    ("Tetley", "Green Tea Lemon & Honey", "Beverages", "Tea", "25 bags", 145, 160),
    ("Lipton", "Yellow Label Tea", "Beverages", "Tea", "250 g", 155, 170),
    ("Brooke Bond", "Red Label Natural Care", "Beverages", "Tea", "250 g", 165, 180),
    ("Colgate", "MaxFresh Blue Gel", "Personal Care", "Oral Care", "150 g", 95, 105),
    ("Colgate", "Visible White Toothpaste", "Personal Care", "Oral Care", "120 g", 125, 135),
    ("Sensodyne", "Repair & Protect", "Personal Care", "Oral Care", "70 g", 165, 180),
    ("Closeup", "Everfresh Red Hot Gel", "Personal Care", "Oral Care", "150 g", 85, 95),
    ("Dove", "Intense Repair Shampoo", "Personal Care", "Hair Care", "340 ml", 385, 425),
    ("Dove", "Deeply Nourishing Body Wash", "Personal Care", "Body Wash", "250 ml", 225, 245),
    ("Head & Shoulders", "Smooth & Silky Shampoo", "Personal Care", "Hair Care", "340 ml", 365, 395),
    ("Pantene", "Advanced Hairfall Solution", "Personal Care", "Hair Care", "340 ml", 345, 375),
    ("L'Oreal", "Paris Total Repair Shampoo", "Personal Care", "Hair Care", "340 ml", 425, 465),
    ("Sunsilk", "Thick & Long Shampoo", "Personal Care", "Hair Care", "340 ml", 245, 265),
    ("Clinic Plus", "Strong & Long Shampoo", "Personal Care", "Hair Care", "340 ml", 195, 215),
    ("Parachute", "Advansed Gold Coconut Hair Oil", "Personal Care", "Hair Care", "300 ml", 165, 180),
    ("Dabur", "Amla Hair Oil", "Personal Care", "Hair Care", "275 ml", 145, 160),
    ("Biotique", "Bio Kelp Protein Shampoo", "Personal Care", "Hair Care", "340 ml", 225, 245),
    ("Himalaya", "Anti-Hair Fall Shampoo", "Personal Care", "Hair Care", "340 ml", 245, 265),
    ("Patanjali", "Kesh Kanti Shampoo", "Personal Care", "Hair Care", "200 ml", 95, 105),
    ("Dettol", "Skincare Bathing Bar", "Personal Care", "Soap", "125 g", 55, 60),
    ("Lifebuoy", "Total 10 Soap", "Personal Care", "Soap", "125 g", 45, 50),
    ("Lux", "Soft Touch Soap", "Personal Care", "Soap", "125 g", 45, 50),
    ("Pears", "Pure & Gentle Soap", "Personal Care", "Soap", "125 g", 55, 60),
    ("Cinthol", "Original Soap", "Personal Care", "Soap", "125 g", 42, 45),
    ("Nivea", "Men Dark Spot Reduction Face Wash", "Personal Care", "Skin Care", "100 g", 165, 180),
    ("Garnier", "Skin Naturals Face Wash", "Personal Care", "Skin Care", "100 g", 145, 160),
    ("Lakme", "Blush & Glow Face Wash", "Beauty & Grooming", "Skin Care", "100 g", 125, 140),
    ("Ponds", "Bright Beauty Face Wash", "Beauty & Grooming", "Skin Care", "100 g", 115, 125),
    ("Gillette", "Fusion 5 Razor", "Personal Care", "Grooming", "1 pc", 425, 465),
    ("Gillette", "Mach3 Razor Cartridges", "Personal Care", "Grooming", "2 pcs", 345, 375),
    ("Veet", "Hair Removal Cream", "Beauty & Grooming", "Grooming", "100 g", 145, 160),
    ("Whisper", "Choice Ultra XL", "Personal Care", "Feminine Hygiene", "20 pcs", 165, 180),
    ("Stayfree", "Secure Cottony Soft XL", "Personal Care", "Feminine Hygiene", "18 pcs", 125, 140),
    ("Surf Excel", "Matic Top Load Liquid", "Home & Cleaning", "Detergent", "1 L", 245, 265),
    ("Surf Excel", "Quick Wash Powder", "Home & Cleaning", "Detergent", "1 kg", 135, 145),
    ("Ariel", "Matic Front Load Liquid", "Home & Cleaning", "Detergent", "2 L", 425, 465),
    ("Tide", "Ultra 3 in 1 Clean", "Home & Cleaning", "Detergent", "1 kg", 145, 160),
    ("Rin", "Advanced Detergent Powder", "Home & Cleaning", "Detergent", "1 kg", 115, 125),
    ("Wheel", "Active 2 in 1", "Home & Cleaning", "Detergent", "1 kg", 65, 72),
    ("Vim", "Bar Lemon", "Home & Cleaning", "Dishwash", "500 g", 55, 60),
    ("Pril", "Advanced Dishwash Gel", "Home & Cleaning", "Dishwash", "750 ml", 145, 160),
    ("Harpic", "Power Plus 10x Rose", "Home & Cleaning", "Cleaner", "500 ml", 99, 109),
    ("Lizol", "Neem Disinfectant", "Home & Cleaning", "Floor Cleaner", "1 L", 175, 190),
    ("Colin", "Glass & Surface Cleaner", "Home & Cleaning", "Cleaner", "500 ml", 95, 105),
    ("Odonil", "Gel Pocket Lavender", "Home & Cleaning", "Air Freshener", "50 g", 55, 60),
    ("Goodknight", "Gold Flash Liquid Vaporizer", "Home & Cleaning", "Repellent", "45 ml", 85, 95),
    ("All Out", "Ultra Power+ Refill", "Home & Cleaning", "Repellent", "45 ml", 75, 85),
    ("Comfort", "Morning Fresh Fabric Conditioner", "Home & Cleaning", "Laundry", "860 ml", 225, 245),
    ("Scotch Brite", "Scrub Sponge", "Kitchen Essentials", "Tools", "1 pc", 35, 40),
    ("Scotch Brite", "Wet Mop Refill", "Kitchen Essentials", "Tools", "1 pc", 145, 160),
    ("Milton", "Steel Lunch Box 3 Tier", "Kitchen Essentials", "Containers", "1 pc", 525, 575),
    ("Milton", "Thermosteel Flask", "Kitchen Essentials", "Bottles", "500 ml", 645, 695),
    ("Prestige", "Hard Anodised Kadai", "Kitchen Essentials", "Cookware", "24 cm", 895, 995),
    ("Hawkins", "Contura Pressure Cooker", "Kitchen Essentials", "Cookware", "3 L", 1245, 1345),
    ("Philips", "LED Bulb 12W", "Electronics", "Lighting", "1 pc", 145, 160),
    ("Philips", "Trimmer BT1235", "Electronics", "Grooming", "1 pc", 1245, 1345),
    ("Boat", "Rockerz 255 Pro+ Earphones", "Electronics", "Audio", "1 pc", 1299, 1499),
    ("Duracell", "AAA Batteries", "Electronics", "Batteries", "4 pcs", 95, 105),
    ("Fresho", "Cauliflower", "Fruits & Vegetables", "Vegetables", "1 pc", 35, 42),
    ("Fresho", "Cabbage", "Fruits & Vegetables", "Vegetables", "1 pc", 28, 32),
    ("Fresho", "Brinjal Purple", "Fruits & Vegetables", "Vegetables", "500 g", 25, 30),
    ("Fresho", "Lady Finger", "Fruits & Vegetables", "Vegetables", "500 g", 32, 38),
    ("Fresho", "Green Peas", "Fruits & Vegetables", "Vegetables", "500 g", 55, 65),
    ("Fresho", "Sweet Corn", "Fruits & Vegetables", "Vegetables", "2 pcs", 35, 42),
    ("Fresho", "Beetroot", "Fruits & Vegetables", "Vegetables", "500 g", 28, 32),
    ("Fresho", "Cucumber", "Fruits & Vegetables", "Vegetables", "500 g", 22, 28),
    ("Fresho", "Bottle Gourd", "Fruits & Vegetables", "Vegetables", "1 pc", 35, 42),
    ("Fresho", "Bitter Gourd", "Fruits & Vegetables", "Vegetables", "500 g", 32, 38),
    ("Fresho", "Ridge Gourd", "Fruits & Vegetables", "Vegetables", "500 g", 28, 32),
    ("Fresho", "French Beans", "Fruits & Vegetables", "Vegetables", "250 g", 28, 32),
    ("Fresho", "Drumstick", "Fruits & Vegetables", "Vegetables", "250 g", 35, 42),
    ("Fresho", "Raw Mango", "Fruits & Vegetables", "Fruits", "500 g", 45, 52),
    ("Fresho", "Watermelon", "Fruits & Vegetables", "Fruits", "1 pc", 55, 65),
    ("Fresho", "Papaya", "Fruits & Vegetables", "Fruits", "1 pc", 65, 75),
    ("Fresho", "Pineapple", "Fruits & Vegetables", "Fruits", "1 pc", 75, 85),
    ("Fresho", "Kiwi Green", "Fruits & Vegetables", "Fruits", "3 pcs", 95, 110),
    ("Fresho", "Orange Nagpur", "Fruits & Vegetables", "Fruits", "1 kg", 85, 95),
    ("Fresho", "Grapes Black", "Fruits & Vegetables", "Fruits", "500 g", 75, 85),
    ("Fresho", "Strawberry", "Fruits & Vegetables", "Fruits", "200 g", 95, 110),
    ("Pampers", "Premium Care Pants", "Baby Care", "Diapers", "32 pcs", 599, 649),
    ("Pampers", "All Round Protection", "Baby Care", "Diapers", "42 pcs", 549, 599),
    ("Huggies", "Wonder Pants", "Baby Care", "Diapers", "32 pcs", 525, 575),
    ("MamyPoko", "Pants Extra Absorb", "Baby Care", "Diapers", "36 pcs", 499, 549),
    ("Johnson's", "Baby Powder", "Baby Care", "Baby Care", "200 g", 125, 140),
    ("Johnson's", "Baby Shampoo", "Baby Care", "Baby Care", "100 ml", 145, 160),
    ("Himalaya", "Baby Cream", "Baby Care", "Baby Care", "100 ml", 95, 105),
    ("Himalaya", "Baby Massage Oil", "Baby Care", "Baby Care", "200 ml", 165, 180),
    ("Sebamed", "Baby Cleansing Bar", "Baby Care", "Baby Care", "150 g", 245, 265),
    ("McCain", "French Fries", "Frozen Food", "Frozen Snacks", "420 g", 115, 125),
    ("McCain", "Aloo Tikki", "Frozen Food", "Frozen Snacks", "400 g", 95, 105),
    ("McCain", "Veggie Nuggets", "Frozen Food", "Frozen Snacks", "325 g", 125, 135),
    ("ITC", "Master Chef Mixed Vegetables", "Frozen Food", "Frozen Veg", "500 g", 95, 105),
    ("ITC", "Master Chef Sweet Corn", "Frozen Food", "Frozen Veg", "500 g", 85, 95),
    ("Godrej", "Yummiez Chicken Nuggets", "Frozen Food", "Frozen Snacks", "400 g", 225, 245),
    ("Venky's", "Chicken Sausages", "Frozen Food", "Frozen Snacks", "250 g", 165, 180),
    ("Pedigree", "Chicken & Vegetables Adult", "Pet Care", "Pet Food", "1.2 kg", 345, 375),
    ("Pedigree", "Meat & Rice Puppy", "Pet Care", "Pet Food", "1.2 kg", 365, 395),
    ("Whiskas", "Tuna Cat Food", "Pet Care", "Pet Food", "480 g", 175, 190),
    ("Drools", "Adult Dog Food Chicken", "Pet Care", "Pet Food", "1.2 kg", 295, 325),
    ("Protinex", "Chocolate Health Supplement", "Health & Wellness", "Supplements", "250 g", 395, 425),
    ("Ensure", "Diabetes Care", "Health & Wellness", "Supplements", "400 g", 645, 695),
    ("Horlicks", "Health & Nutrition Drink", "Health & Wellness", "Supplements", "500 g", 285, 310),
    ("Bournvita", "Health Drink", "Health & Wellness", "Supplements", "500 g", 245, 265),
    ("Complan", "Chocolate Flavour", "Health & Wellness", "Supplements", "500 g", 265, 285),
    ("Himalaya", "Liv.52 Tablets", "Health & Wellness", "Ayurveda", "100 tablets", 145, 160),
    ("Dabur", "Chyawanprash", "Health & Wellness", "Ayurveda", "500 g", 185, 200),
    ("Durex", "Extra Thin Condoms", "Health & Wellness", "Wellness", "10 pcs", 275, 295),
    ("Mankind", "Prega News", "Health & Wellness", "Wellness", "1 pc", 55, 60),
    ("English Oven", "Zero Maida Bread", "Bakery", "Bread", "400 g", 55, 60),
    ("Modern", "Brown Bread", "Bakery", "Bread", "400 g", 48, 52),
    ("Harvest Gold", "White Bread", "Bakery", "Bread", "400 g", 42, 45),
    ("Britannia", "Rusk Premium Bake", "Bakery", "Rusk", "300 g", 55, 60),
    ("Priya Gold", "Butter Delite", "Bakery", "Biscuits", "150 g", 35, 40),
    ("Unibic", "Choco Chip Cookies", "Bakery", "Biscuits", "450 g", 125, 140),
    ("McVitie's", "Digestive Biscuits", "Bakery", "Biscuits", "250 g", 85, 95),
    ("Karachi Bakery", "Osmania Biscuit", "Bakery", "Biscuits", "400 g", 165, 180),
    ("MTR", "Rava Idli Mix", "Frozen & Instant", "Instant Mix", "500 g", 85, 95),
    ("MTR", "Dosa Mix", "Frozen & Instant", "Instant Mix", "500 g", 95, 105),
    ("Gits", "Gulab Jamun Mix", "Frozen & Instant", "Instant Mix", "200 g", 65, 72),
    ("Gits", "Dhokla Mix", "Frozen & Instant", "Instant Mix", "200 g", 55, 60),
    ("Yippee", "Power Up Atta Noodles", "Frozen & Instant", "Noodles", "280 g", 55, 60),
    ("Top Ramen", "Curry Noodles", "Frozen & Instant", "Noodles", "70 g", 14, 16),
    ("Wai Wai", "Ready To Eat Noodles", "Frozen & Instant", "Noodles", "75 g", 15, 18),
    ("Nissin", "Cup Noodles Veggie", "Frozen & Instant", "Noodles", "70 g", 45, 50),
    ("Bambino", "Vermicelli Roasted", "Staples & Grains", "Vermicelli", "400 g", 55, 60),
    ("Bambino", "Macaroni", "Staples & Grains", "Pasta", "400 g", 65, 72),
    ("Pillsbury", "Atta Whole Wheat", "Staples & Grains", "Atta", "5 kg", 265, 285),
    ("Nature Fresh", "Refined Sunflower Oil", "Staples & Grains", "Oil", "1 L", 135, 145),
    ("Gemini", "Sunflower Oil", "Staples & Grains", "Oil", "1 L", 128, 138),
    ("Dhara", "Mustard Oil", "Staples & Grains", "Oil", "1 L", 148, 160),
    ("Figaro", "Olive Oil", "Staples & Grains", "Oil", "250 ml", 425, 465),
    ("Borges", "Extra Virgin Olive Oil", "Staples & Grains", "Oil", "250 ml", 545, 595),
    ("Del Monte", "Tomato Ketchup", "Staples & Grains", "Sauces", "950 g", 135, 145),
    ("Veeba", "Eggless Mayonnaise", "Staples & Grains", "Sauces", "250 g", 85, 95),
    ("Tabasco", "Red Pepper Sauce", "Staples & Grains", "Sauces", "60 ml", 195, 215),
    ("American Garden", "Pancake Syrup", "Staples & Grains", "Spreads", "710 ml", 425, 465),
    ("Nutella", "Hazelnut Spread", "Staples & Grains", "Spreads", "350 g", 325, 350),
    ("Pintola", "All Natural Peanut Butter", "Staples & Grains", "Spreads", "350 g", 225, 245),
    ("Alpino", "Natural Peanut Butter", "Staples & Grains", "Spreads", "400 g", 245, 265),
    ("Quaker", "Oats", "Dairy & Breakfast", "Cereals", "1 kg", 185, 200),
    ("Saffola", "Masala Oats Classic Masala", "Dairy & Breakfast", "Cereals", "500 g", 145, 160),
    ("Kellogg's", "Chocos Moons & Stars", "Dairy & Breakfast", "Cereals", "375 g", 175, 190),
    ("Kellogg's", "Muesli Fruit & Nut", "Dairy & Breakfast", "Cereals", "500 g", 245, 265),
    ("Bagrry's", "White Oats", "Dairy & Breakfast", "Cereals", "1 kg", 165, 180),
    ("MTR", "Badam Mix", "Dairy & Breakfast", "Health Mix", "500 g", 245, 265),
    ("Organic India", "Tulsi Green Tea", "Beverages", "Tea", "25 bags", 165, 180),
    ("Organic India", "Tulsi Original Tea", "Beverages", "Tea", "25 bags", 155, 170),
    ("24 Mantra", "Organic Toor Dal", "Staples & Grains", "Dal", "500 g", 95, 105),
    ("24 Mantra", "Organic Brown Rice", "Staples & Grains", "Rice", "1 kg", 145, 160),
    ("Pro Nature", "Organic Jaggery Powder", "Staples & Grains", "Jaggery", "500 g", 85, 95),
    ("Tata Sampann", "Himalayan Pink Salt", "Staples & Grains", "Salt", "500 g", 65, 72),
    ("Keya", "Oregano Seasoning", "Staples & Grains", "Spices", "40 g", 45, 50),
    ("Keya", "Pizza Seasoning", "Staples & Grains", "Spices", "40 g", 45, 50),
    ("Smith & Jones", "Pasta Masala", "Staples & Grains", "Spices", "50 g", 35, 40),
    ("Badshah", "Pav Bhaji Masala", "Staples & Grains", "Spices", "100 g", 55, 60),
    ("Catch", "Chat Masala", "Staples & Grains", "Spices", "100 g", 55, 60),
    ("MTR", "Rasam Powder", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Eastern", "Chicken Masala", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Gowardhan", "Paneer", "Dairy & Breakfast", "Paneer", "200 g", 88, 95),
    ("Gowardhan", "Ghee", "Dairy & Breakfast", "Ghee", "500 ml", 335, 365),
    ("Ananda", "Toned Milk", "Dairy & Breakfast", "Milk", "500 ml", 52, 55),
    ("Heritage", "Full Cream Milk", "Dairy & Breakfast", "Milk", "1 L", 70, 74),
    ("Nandini", "Goodlife Toned Milk", "Dairy & Breakfast", "Milk", "500 ml", 50, 54),
    ("Verka", "Fresh Milk", "Dairy & Breakfast", "Milk", "500 ml", 48, 52),
    ("Epigamia", "Greek Yogurt Natural", "Dairy & Breakfast", "Yogurt", "400 g", 165, 180),
    ("Epigamia", "Greek Yogurt Strawberry", "Dairy & Breakfast", "Yogurt", "85 g", 35, 40),
    ("Yakult", "Probiotic Drink", "Dairy & Breakfast", "Probiotic", "5 pcs", 85, 95),
    ("Actimel", "Probiotic Drink", "Dairy & Breakfast", "Probiotic", "4 pcs", 95, 105),
    ("Bikano", "Soan Papdi", "Snacks & Munchies", "Sweets", "400 g", 125, 140),
    ("Bikano", "Mixture", "Snacks & Munchies", "Namkeen", "200 g", 50, 55),
    ("Cremica", "Marie Biscuits", "Snacks & Munchies", "Biscuits", "250 g", 45, 50),
    ("Anmol", "Glucose Biscuits", "Snacks & Munchies", "Biscuits", "400 g", 55, 60),
    ("Too Yumm", "Karare Masala Punch", "Snacks & Munchies", "Snacks", "60 g", 20, 20),
    ("Too Yumm", "Veggie Stix Sour Cream", "Snacks & Munchies", "Snacks", "50 g", 20, 20),
    ("Doritos", "Nacho Cheese", "Snacks & Munchies", "Chips", "84 g", 95, 105),
    ("Cheetos", "Flamin Hot", "Snacks & Munchies", "Snacks", "50 g", 45, 50),
    ("Ferrero", "Nutella B-Ready", "Snacks & Munchies", "Snacks", "88 g", 125, 140),
    ("Lotte", "Pepero Choco Sticks", "Snacks & Munchies", "Snacks", "32 g", 45, 50),
    ("MTR", "Gulab Jamun Ready Mix", "Snacks & Munchies", "Sweets", "175 g", 55, 60),
    ("Wagh Bakri", "Premium Tea", "Beverages", "Tea", "250 g", 155, 170),
    ("Society", "Tea Premium", "Beverages", "Tea", "250 g", 145, 160),
    ("Davidoff", "Cafe Instant Coffee", "Beverages", "Coffee", "100 g", 425, 465),
    ("Continental", "Speciale Coffee", "Beverages", "Coffee", "200 g", 345, 375),
    ("Beardo", "Beard Oil", "Beauty & Grooming", "Grooming", "30 ml", 345, 375),
    ("Ustraa", "Face Wash", "Beauty & Grooming", "Grooming", "100 ml", 245, 265),
    ("Axe", "Dark Temptation Deodorant", "Beauty & Grooming", "Grooming", "150 ml", 225, 245),
    ("Fogg", "Marco Body Spray", "Beauty & Grooming", "Grooming", "120 ml", 195, 215),
    ("Park Avenue", "Good Morning Deo", "Beauty & Grooming", "Grooming", "150 ml", 185, 200),
    ("Biotique", "Bio Honey Gel Moisturiser", "Beauty & Grooming", "Skin Care", "190 ml", 195, 215),
    ("Lotus Herbals", "Safe Sun SPF 50", "Beauty & Grooming", "Skin Care", "100 g", 345, 375),
    ("Maybelline", "Fit Me Foundation", "Beauty & Grooming", "Makeup", "30 ml", 425, 465),
    ("L'Oreal", "Revitalift Serum", "Beauty & Grooming", "Skin Care", "30 ml", 645, 695),
    ("Borosil", "Glass Lunch Box", "Kitchen Essentials", "Containers", "1 pc", 425, 465),
    ("Cello", "Water Bottle", "Kitchen Essentials", "Bottles", "1 L", 245, 265),
    ("Milton", "Casserole Set", "Kitchen Essentials", "Containers", "3 pcs", 895, 995),
    ("Amazon Basics", "Extension Board", "Electronics", "Accessories", "1 pc", 445, 485),
    ("Syska", "LED Bulb 9W", "Electronics", "Lighting", "1 pc", 85, 95),
    ("Mi", "Smart LED Bulb", "Electronics", "Lighting", "1 pc", 645, 695),
    ("Portronics", "Car Charger", "Electronics", "Accessories", "1 pc", 345, 375),
    ("Ambrane", "Power Bank 10000mAh", "Electronics", "Accessories", "1 pc", 899, 999),
    ("Fresho", "Mint Leaves", "Fruits & Vegetables", "Herbs", "100 g", 12, 15),
    ("Fresho", "Curry Leaves", "Fruits & Vegetables", "Herbs", "100 g", 10, 12),
    ("Fresho", "Green Chilli", "Fruits & Vegetables", "Vegetables", "250 g", 18, 22),
    ("Fresho", "Red Capsicum", "Fruits & Vegetables", "Vegetables", "250 g", 45, 52),
    ("Fresho", "Yellow Capsicum", "Fruits & Vegetables", "Vegetables", "250 g", 55, 62),
    ("Fresho", "Baby Corn", "Fruits & Vegetables", "Vegetables", "200 g", 45, 52),
    ("Fresho", "Avocado", "Fruits & Vegetables", "Fruits", "1 pc", 95, 110),
    ("Fresho", "Blueberry", "Fruits & Vegetables", "Fruits", "125 g", 145, 165),
    ("Fresho", "Dragon Fruit", "Fruits & Vegetables", "Fruits", "1 pc", 85, 95),
    ("Fresho", "Muskmelon", "Fruits & Vegetables", "Fruits", "1 pc", 45, 52),
    ("Fresho", "Coconut", "Fruits & Vegetables", "Fruits", "1 pc", 35, 42),
    ("Fresho", "Amla", "Fruits & Vegetables", "Fruits", "250 g", 28, 32),
    ("Fresho", "Guava", "Fruits & Vegetables", "Fruits", "500 g", 45, 52),
    ("Fresho", "Pear Green", "Fruits & Vegetables", "Fruits", "500 g", 95, 110),
    ("Fresho", "Plum", "Fruits & Vegetables", "Fruits", "500 g", 125, 140),
    ("Fresho", "Cherry", "Fruits & Vegetables", "Fruits", "200 g", 195, 215),
    ("Fresho", "Jackfruit Raw", "Fruits & Vegetables", "Fruits", "500 g", 55, 62),
    ("Fresho", "Sweet Potato", "Fruits & Vegetables", "Vegetables", "500 g", 35, 42),
    ("Fresho", "Arbi", "Fruits & Vegetables", "Vegetables", "500 g", 42, 48),
    ("Fresho", "Colocasia", "Fruits & Vegetables", "Vegetables", "500 g", 38, 44),
    ("Fresho", "Yam", "Fruits & Vegetables", "Vegetables", "500 g", 45, 52),
    ("Fresho", "Turnip", "Fruits & Vegetables", "Vegetables", "500 g", 28, 32),
    ("Fresho", "Radish White", "Fruits & Vegetables", "Vegetables", "500 g", 22, 28),
    ("Fresho", "Pumpkin", "Fruits & Vegetables", "Vegetables", "500 g", 25, 30),
    ("Fresho", "Zucchini Green", "Fruits & Vegetables", "Vegetables", "500 g", 65, 72),
    ("Fresho", "Lettuce Iceberg", "Fruits & Vegetables", "Vegetables", "1 pc", 45, 52),
    ("Fresho", "Broccoli", "Fruits & Vegetables", "Vegetables", "500 g", 95, 110),
    ("Fresho", "Celery", "Fruits & Vegetables", "Vegetables", "250 g", 55, 62),
    ("Fresho", "Leeks", "Fruits & Vegetables", "Vegetables", "250 g", 65, 72),
    ("Fresho", "Spring Onion", "Fruits & Vegetables", "Vegetables", "250 g", 22, 28),
    ("Fresho", "Parsley", "Fruits & Vegetables", "Herbs", "50 g", 25, 30),
    ("Fresho", "Basil", "Fruits & Vegetables", "Herbs", "50 g", 35, 42),
    ("Fresho", "Thyme", "Fruits & Vegetables", "Herbs", "50 g", 45, 52),
    ("Fresho", "Rosemary", "Fruits & Vegetables", "Herbs", "50 g", 55, 62),
    ("Fresho", "Dill Leaves", "Fruits & Vegetables", "Herbs", "100 g", 28, 32),
    ("Fresho", "Fenugreek Leaves", "Fruits & Vegetables", "Herbs", "250 g", 22, 28),
    ("Fresho", "Mustard Leaves", "Fruits & Vegetables", "Vegetables", "250 g", 25, 30),
    ("Fresho", "Bathua", "Fruits & Vegetables", "Vegetables", "250 g", 22, 28),
    ("Fresho", "Amaranth Leaves", "Fruits & Vegetables", "Vegetables", "250 g", 25, 30),
    ("Fresho", "Colocasia Leaves", "Fruits & Vegetables", "Vegetables", "250 g", 28, 32),
    ("Fresho", "Drumstick Leaves", "Fruits & Vegetables", "Herbs", "100 g", 35, 42),
    ("Fresho", "Methi Seeds", "Staples & Grains", "Spices", "100 g", 25, 30),
    ("Fresho", "Saunf", "Staples & Grains", "Spices", "100 g", 45, 52),
    ("Fresho", "Jeera", "Staples & Grains", "Spices", "100 g", 85, 95),
    ("Fresho", "Dhania Seeds", "Staples & Grains", "Spices", "100 g", 45, 52),
    ("Fresho", "Rai", "Staples & Grains", "Spices", "100 g", 35, 40),
    ("Fresho", "Ajwain", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Kalijiri", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Fresho", "Tej Patta", "Staples & Grains", "Spices", "50 g", 35, 40),
    ("Fresho", "Dalchini", "Staples & Grains", "Spices", "50 g", 55, 62),
    ("Fresho", "Laung", "Staples & Grains", "Spices", "50 g", 85, 95),
    ("Fresho", "Elaichi Green", "Staples & Grains", "Spices", "50 g", 125, 140),
    ("Fresho", "Kali Mirch Whole", "Staples & Grains", "Spices", "100 g", 95, 105),
    ("Fresho", "Hing", "Staples & Grains", "Spices", "25 g", 45, 52),
    ("Fresho", "Kesar", "Staples & Grains", "Spices", "1 g", 125, 140),
    ("Fresho", "Jaiphal", "Staples & Grains", "Spices", "50 g", 145, 160),
    ("Fresho", "Javitri", "Staples & Grains", "Spices", "25 g", 95, 105),
    ("Fresho", "Star Anise", "Staples & Grains", "Spices", "50 g", 85, 95),
    ("Fresho", "Bay Leaf", "Staples & Grains", "Spices", "50 g", 35, 40),
    ("Fresho", "Tamarind", "Staples & Grains", "Spices", "200 g", 45, 52),
    ("Fresho", "Dry Red Chilli", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Kashmiri Chilli", "Staples & Grains", "Spices", "100 g", 85, 95),
    ("Fresho", "Turmeric Powder", "Staples & Grains", "Spices", "200 g", 65, 72),
    ("Fresho", "Red Chilli Powder", "Staples & Grains", "Spices", "200 g", 85, 95),
    ("Fresho", "Coriander Powder", "Staples & Grains", "Spices", "200 g", 55, 62),
    ("Fresho", "Garam Masala Powder", "Staples & Grains", "Spices", "100 g", 75, 85),
    ("Fresho", "Kitchen King Masala", "Staples & Grains", "Spices", "100 g", 72, 78),
    ("Fresho", "Meat Masala", "Staples & Grains", "Spices", "100 g", 68, 75),
    ("Fresho", "Fish Masala", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Fresho", "Chana Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Rajma Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Paneer Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Biryani Masala", "Staples & Grains", "Spices", "100 g", 65, 72),
    ("Fresho", "Tandoori Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Chaat Masala", "Staples & Grains", "Spices", "100 g", 45, 52),
    ("Fresho", "Sambar Powder", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Rasam Powder", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Pav Bhaji Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Misal Masala", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Pani Puri Masala", "Staples & Grains", "Spices", "100 g", 45, 52),
    ("Fresho", "Pizza Seasoning", "Staples & Grains", "Spices", "40 g", 45, 50),
    ("Fresho", "Oregano", "Staples & Grains", "Spices", "40 g", 45, 50),
    ("Fresho", "Chilli Flakes", "Staples & Grains", "Spices", "40 g", 35, 40),
    ("Fresho", "Black Pepper Powder", "Staples & Grains", "Spices", "100 g", 95, 105),
    ("Fresho", "White Pepper Powder", "Staples & Grains", "Spices", "100 g", 125, 140),
    ("Fresho", "Dry Mango Powder", "Staples & Grains", "Spices", "100 g", 55, 62),
    ("Fresho", "Black Salt Powder", "Staples & Grains", "Spices", "200 g", 35, 40),
    ("Fresho", "Rock Salt", "Staples & Grains", "Salt", "1 kg", 45, 52),
    ("Fresho", "Sendha Namak", "Staples & Grains", "Salt", "500 g", 35, 40),
    ("Fresho", "Jaggery Block", "Staples & Grains", "Jaggery", "500 g", 55, 62),
    ("Fresho", "Jaggery Powder", "Staples & Grains", "Jaggery", "500 g", 65, 72),
    ("Fresho", "Brown Sugar", "Staples & Grains", "Sugar", "500 g", 65, 72),
    ("Fresho", "Powdered Sugar", "Staples & Grains", "Sugar", "500 g", 55, 62),
    ("Fresho", "Coconut Sugar", "Staples & Grains", "Sugar", "500 g", 145, 160),
    ("Fresho", "Palm Jaggery", "Staples & Grains", "Jaggery", "500 g", 85, 95),
    ("Fresho", "Date Palm Jaggery", "Staples & Grains", "Jaggery", "500 g", 95, 105),
    ("Fresho", "Organic Honey", "Staples & Grains", "Honey", "500 g", 285, 310),
    ("Fresho", "Multiflora Honey", "Staples & Grains", "Honey", "500 g", 245, 265),
    ("Fresho", "Acacia Honey", "Staples & Grains", "Honey", "500 g", 345, 375),
    ("Fresho", "Wild Forest Honey", "Staples & Grains", "Honey", "500 g", 425, 465),
    ("Fresho", "Manuka Honey", "Staples & Grains", "Honey", "250 g", 645, 695),
    ("Fresho", "Saffron Kashmiri", "Staples & Grains", "Spices", "1 g", 245, 265),
    ("Fresho", "Vanilla Extract", "Staples & Grains", "Baking", "30 ml", 145, 160),
    ("Fresho", "Baking Powder", "Staples & Grains", "Baking", "100 g", 45, 52),
    ("Fresho", "Baking Soda", "Staples & Grains", "Baking", "100 g", 35, 40),
    ("Fresho", "Cocoa Powder", "Staples & Grains", "Baking", "150 g", 125, 140),
    ("Fresho", "Custard Powder", "Staples & Grains", "Baking", "100 g", 55, 62),
    ("Fresho", "Corn Flour", "Staples & Grains", "Flour", "500 g", 45, 52),
    ("Fresho", "Rice Flour", "Staples & Grains", "Flour", "500 g", 55, 62),
    ("Fresho", "Besan", "Staples & Grains", "Flour", "500 g", 65, 72),
    ("Fresho", "Rava Sooji", "Staples & Grains", "Flour", "500 g", 45, 52),
    ("Fresho", "Maida", "Staples & Grains", "Flour", "500 g", 35, 40),
    ("Fresho", "Wheat Flour", "Staples & Grains", "Flour", "1 kg", 55, 62),
    ("Fresho", "Multigrain Flour", "Staples & Grains", "Flour", "1 kg", 75, 85),
    ("Fresho", "Buckwheat Flour", "Staples & Grains", "Flour", "500 g", 125, 140),
    ("Fresho", "Quinoa", "Staples & Grains", "Grains", "500 g", 245, 265),
    ("Fresho", "Chia Seeds", "Staples & Grains", "Seeds", "200 g", 185, 200),
    ("Fresho", "Flax Seeds", "Staples & Grains", "Seeds", "200 g", 95, 105),
    ("Fresho", "Pumpkin Seeds", "Staples & Grains", "Seeds", "200 g", 145, 160),
    ("Fresho", "Sunflower Seeds", "Staples & Grains", "Seeds", "200 g", 85, 95),
    ("Fresho", "Watermelon Seeds", "Staples & Grains", "Seeds", "200 g", 95, 105),
    ("Fresho", "Muskmelon Seeds", "Staples & Grains", "Seeds", "200 g", 85, 95),
    ("Fresho", "Sesame Seeds White", "Staples & Grains", "Seeds", "200 g", 65, 72),
    ("Fresho", "Sesame Seeds Black", "Staples & Grains", "Seeds", "200 g", 85, 95),
    ("Fresho", "Poppy Seeds", "Staples & Grains", "Seeds", "100 g", 125, 140),
    ("Fresho", "Basil Seeds", "Staples & Grains", "Seeds", "200 g", 95, 105),
    ("Fresho", "Mixed Dry Fruits", "Staples & Grains", "Dry Fruits", "500 g", 645, 695),
    ("Fresho", "Almonds California", "Staples & Grains", "Dry Fruits", "500 g", 545, 595),
    ("Fresho", "Cashews Whole", "Staples & Grains", "Dry Fruits", "500 g", 645, 695),
    ("Fresho", "Walnuts", "Staples & Grains", "Dry Fruits", "500 g", 545, 595),
    ("Fresho", "Pistachios", "Staples & Grains", "Dry Fruits", "500 g", 745, 795),
    ("Fresho", "Raisins Black", "Staples & Grains", "Dry Fruits", "500 g", 245, 265),
    ("Fresho", "Raisins Golden", "Staples & Grains", "Dry Fruits", "500 g", 285, 310),
    ("Fresho", "Dates Ajwa", "Staples & Grains", "Dry Fruits", "500 g", 445, 485),
    ("Fresho", "Dates Medjool", "Staples & Grains", "Dry Fruits", "500 g", 545, 595),
    ("Fresho", "Apricots Dried", "Staples & Grains", "Dry Fruits", "200 g", 245, 265),
    ("Fresho", "Prunes Dried", "Staples & Grains", "Dry Fruits", "200 g", 285, 310),
    ("Fresho", "Figs Dried", "Staples & Grains", "Dry Fruits", "200 g", 345, 375),
    ("Fresho", "Cranberries Dried", "Staples & Grains", "Dry Fruits", "200 g", 245, 265),
    ("Fresho", "Blueberries Dried", "Staples & Grains", "Dry Fruits", "200 g", 345, 375),
    ("Fresho", "Goji Berries", "Staples & Grains", "Dry Fruits", "200 g", 445, 485),
    ("Fresho", "Trail Mix", "Staples & Grains", "Dry Fruits", "500 g", 445, 485),
    ("Fresho", "Makhana Fox Nuts", "Staples & Grains", "Snacks", "200 g", 245, 265),
    ("Fresho", "Roasted Makhana", "Staples & Grains", "Snacks", "100 g", 145, 160),
    ("Fresho", "Peanuts Roasted", "Staples & Grains", "Snacks", "500 g", 145, 160),
    ("Fresho", "Almonds Roasted", "Staples & Grains", "Snacks", "200 g", 345, 375),
    ("Fresho", "Cashews Roasted", "Staples & Grains", "Snacks", "200 g", 445, 485),
    ("Fresho", "Mixed Seeds Roasted", "Staples & Grains", "Snacks", "200 g", 185, 200),
    ("Fresho", "Energy Bar Mixed Nuts", "Snacks & Munchies", "Health Snacks", "6 pcs", 245, 265),
    ("Fresho", "Protein Bar Chocolate", "Snacks & Munchies", "Health Snacks", "6 pcs", 345, 375),
    ("Fresho", "Granola Bar Honey", "Snacks & Munchies", "Health Snacks", "6 pcs", 245, 265),
    ("Fresho", "Muesli Bar Fruit", "Snacks & Munchies", "Health Snacks", "6 pcs", 225, 245),
    ("Fresho", "Oats Bar Chocolate", "Snacks & Munchies", "Health Snacks", "6 pcs", 195, 215),
    ("Fresho", "Rice Cakes Plain", "Snacks & Munchies", "Health Snacks", "150 g", 85, 95),
    ("Fresho", "Rice Cakes Multigrain", "Snacks & Munchies", "Health Snacks", "150 g", 95, 105),
    ("Fresho", "Multigrain Chips", "Snacks & Munchies", "Chips", "60 g", 45, 50),
    ("Fresho", "Baked Chips Masala", "Snacks & Munchies", "Chips", "60 g", 45, 50),
    ("Fresho", "Veggie Chips", "Snacks & Munchies", "Chips", "60 g", 55, 62),
    ("Fresho", "Sweet Potato Chips", "Snacks & Munchies", "Chips", "60 g", 55, 62),
    ("Fresho", "Banana Chips", "Snacks & Munchies", "Chips", "100 g", 65, 72),
    ("Fresho", "Tapioca Chips", "Snacks & Munchies", "Chips", "100 g", 55, 62),
    ("Fresho", "Jackfruit Chips", "Snacks & Munchies", "Chips", "100 g", 75, 85),
    ("Fresho", "Arrowroot Chips", "Snacks & Munchies", "Chips", "100 g", 65, 72),
    ("Fresho", "Ragi Chips", "Snacks & Munchies", "Chips", "60 g", 55, 62),
    ("Fresho", "Quinoa Chips", "Snacks & Munchies", "Chips", "60 g", 65, 72),
    ("Fresho", "Lentil Chips", "Snacks & Munchies", "Chips", "60 g", 55, 62),
    ("Fresho", "Chickpea Puffs", "Snacks & Munchies", "Snacks", "60 g", 45, 50),
    ("Fresho", "Protein Puffs", "Snacks & Munchies", "Snacks", "60 g", 55, 62),
    ("Fresho", "Roasted Chana", "Snacks & Munchies", "Namkeen", "200 g", 55, 62),
    ("Fresho", "Roasted Makhana Masala", "Snacks & Munchies", "Namkeen", "100 g", 145, 160),
    ("Fresho", "Roasted Peanuts Masala", "Snacks & Munchies", "Namkeen", "200 g", 65, 72),
    ("Fresho", "Roasted Almonds Salted", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Roasted Cashews Salted", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Trail Mix Spicy", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Trail Mix Sweet", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Energy Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Protein Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Diabetic Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Heart Healthy Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Weight Management Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Immunity Booster Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Antioxidant Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Omega 3 Mix", "Snacks & Munchies", "Namkeen", "200 g", 385, 425),
    ("Fresho", "Fiber Rich Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Calcium Rich Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Iron Rich Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Vitamin Rich Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Mineral Rich Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Superfood Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Organic Mix", "Snacks & Munchies", "Namkeen", "200 g", 385, 425),
    ("Fresho", "Vegan Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Gluten Free Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Keto Mix", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Paleo Mix", "Snacks & Munchies", "Namkeen", "200 g", 385, 425),
    ("Fresho", "Low Carb Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "High Protein Mix", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Low Fat Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Sugar Free Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "No Added Sugar Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Zero Cholesterol Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Trans Fat Free Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Preservative Free Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Artificial Color Free Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "All Natural Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Farm Fresh Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Handpicked Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Premium Select Mix", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Chef's Special Mix", "Snacks & Munchies", "Namkeen", "200 g", 385, 425),
    ("Fresho", "Gourmet Mix", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Artisan Mix", "Snacks & Munchies", "Namkeen", "200 g", 385, 425),
    ("Fresho", "Heritage Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Traditional Mix", "Snacks & Munchies", "Namkeen", "200 g", 285, 310),
    ("Fresho", "Classic Mix", "Snacks & Munchies", "Namkeen", "200 g", 245, 265),
    ("Fresho", "Signature Mix", "Snacks & Munchies", "Namkeen", "200 g", 345, 375),
    ("Fresho", "Exclusive Mix", "Snacks & Munchies", "Namkeen", "200 g", 445, 485),
    ("Fresho", "Limited Edition Mix", "Snacks & Munchies", "Namkeen", "200 g", 545, 595),
]


def product_key(brand: str, name: str, unit: str) -> tuple[str, str, str]:
    return (brand.strip().lower(), name.strip().lower(), unit.strip().lower())


def main() -> None:
    existing: set[tuple[str, str, str]] = set()
    if CATALOG.exists():
        data = json.loads(CATALOG.read_text(encoding="utf-8"))
        for p in data.get("products", []):
            existing.add(product_key(p["brand"], p["name"], p["unit"]))

    extra: list[tuple] = []
    seen: set[tuple[str, str, str]] = set()
    for row in TEMPLATES:
        brand, name, cat, sub, unit, price, mrp = row
        key = product_key(brand, name, unit)
        if key in existing or key in seen:
            continue
        seen.add(key)
        extra.append(row)
        if len(extra) >= 300:
            break

    lines = ["# Auto-generated 300 additional unique Indian grocery products", "EXTRA_SEED: list[tuple] = ["]
    for row in extra:
        lines.append(f"    {row!r},")
    lines.append("]")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(extra)} products to {OUT}")


if __name__ == "__main__":
    main()
