"""200+ additional unique Indian grocery products for OneLink shop."""

# (brand, name, category, subCategory, unit, price, mrp)
BULK_SEED: list[tuple] = [
    ("Amul", "Spray Cream", "Dairy & Breakfast", "Cream", "250 g", 125, 135),
    ("Amul", "Milkshake Kool Koko", "Dairy & Breakfast", "Milk", "200 ml", 25, 28),
    ("Amul", "Probiotic Lassi", "Dairy & Breakfast", "Lassi", "200 ml", 20, 22),
    ("Amul", "Shrikhand Elaichi", "Dairy & Breakfast", "Dessert", "200 g", 65, 70),
    ("Amul", "Fresh Cream", "Dairy & Breakfast", "Cream", "200 ml", 58, 62),
    ("Mother Dairy", "Mishti Doi", "Dairy & Breakfast", "Curd", "85 g", 25, 28),
    ("Mother Dairy", "Flavoured Milk Badam", "Dairy & Breakfast", "Milk", "200 ml", 22, 25),
    ("Mother Dairy", "Cow Ghee", "Dairy & Breakfast", "Ghee", "500 ml", 345, 365),
    ("Britannia", "NutriChoice Digestive", "Dairy & Breakfast", "Biscuits", "100 g", 30, 35),
    ("Britannia", "Milk Bikis", "Dairy & Breakfast", "Biscuits", "200 g", 35, 40),
    ("Britannia", "50-50 Sweet & Salty", "Snacks & Munchies", "Biscuits", "150 g", 30, 35),
    ("Britannia", "Little Hearts", "Snacks & Munchies", "Biscuits", "75 g", 25, 28),
    ("Nestle", "Munch Nuts", "Snacks & Munchies", "Chocolate", "36 g", 20, 20),
    ("Nestle", "KitKat 4 Finger", "Snacks & Munchies", "Chocolate", "38.5 g", 25, 30),
    ("Nestle", "Milkybar", "Snacks & Munchies", "Chocolate", "42 g", 25, 28),
    ("Cadbury", "5 Star", "Snacks & Munchies", "Chocolate", "40 g", 20, 20),
    ("Cadbury", "Perk", "Snacks & Munchies", "Chocolate", "30 g", 15, 15),
    ("Cadbury", "Gems", "Snacks & Munchies", "Chocolate", "18.2 g", 10, 10),
    ("Ferrero", "Rocher 3 Pcs", "Snacks & Munchies", "Chocolate", "37.5 g", 125, 135),
    ("Lotte", "Choco Pie", "Snacks & Munchies", "Cakes", "168 g", 55, 60),
    ("Haldiram's", "Aloo Bhujia", "Snacks & Munchies", "Namkeen", "400 g", 95, 105),
    ("Haldiram's", "Moong Dal", "Snacks & Munchies", "Namkeen", "200 g", 55, 60),
    ("Haldiram's", "Punjabi Tadka", "Snacks & Munchies", "Namkeen", "150 g", 45, 50),
    ("Bikaji", "All In One", "Snacks & Munchies", "Namkeen", "200 g", 55, 60),
    ("Bikaji", "Bikaneri Bhujia", "Snacks & Munchies", "Namkeen", "400 g", 85, 95),
    ("Pringles", "Original", "Snacks & Munchies", "Chips", "107 g", 110, 120),
    ("Doritos", "Nacho Cheese", "Snacks & Munchies", "Chips", "84 g", 55, 60),
    ("Cheetos", "Masala Balls", "Snacks & Munchies", "Snacks", "50 g", 20, 20),
    ("Too Yumm", "Karela Chips", "Snacks & Munchies", "Chips", "50 g", 20, 20),
    ("Lay's", "American Style Cream & Onion", "Snacks & Munchies", "Chips", "52 g", 20, 20),
    ("Sprite", "Zero Sugar", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Fanta", "Orange", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Limca", "Lemon Drink", "Beverages", "Soft Drinks", "750 ml", 40, 45),
    ("Appy", "Fizz", "Beverages", "Juice", "600 ml", 35, 40),
    ("Tropicana", "Orange Delight", "Beverages", "Juice", "1 L", 120, 130),
    ("Minute Maid", "Pulpy Orange", "Beverages", "Juice", "1 L", 105, 115),
    ("Raw Pressery", "Cold Pressed Orange", "Beverages", "Juice", "250 ml", 65, 75),
    ("B Natural", "Mixed Fruit", "Beverages", "Juice", "1 L", 95, 105),
    ("Kinley", "Packaged Water", "Beverages", "Water", "1 L", 18, 20),
    ("Aquafina", "Packaged Water", "Beverages", "Water", "1 L", 18, 20),
    ("Red Label", "Natural Care Tea", "Beverages", "Tea", "250 g", 135, 145),
    ("Brooke Bond", "Taj Mahal Tea", "Beverages", "Tea", "250 g", 155, 165),
    ("Davidoff", "Instant Coffee", "Beverages", "Coffee", "100 g", 425, 450),
    ("Continental", "Xtra Strong Coffee", "Beverages", "Coffee", "50 g", 95, 105),
    ("Monster", "Energy Drink", "Beverages", "Energy", "350 ml", 95, 105),
    ("Sting", "Energy Drink", "Beverages", "Energy", "250 ml", 20, 20),
    ("Patanjali", "Cow Ghee", "Staples & Grains", "Ghee", "500 ml", 325, 345),
    ("Organic Tattva", "Brown Rice", "Staples & Grains", "Rice", "1 kg", 145, 155),
    ("24 Mantra", "Sonamasuri Rice", "Staples & Grains", "Rice", "1 kg", 95, 105),
    ("Kohinoor", "Basmati Rice", "Staples & Grains", "Rice", "1 kg", 155, 165),
    ("Pillsbury", "Chakki Fresh Atta", "Staples & Grains", "Atta", "5 kg", 265, 285),
    ("Nature Fresh", "Refined Sunflower Oil", "Staples & Grains", "Oil", "1 L", 125, 135),
    ("Dhara", "Mustard Oil", "Staples & Grains", "Oil", "1 L", 165, 175),
    ("Tata", "Sampann Moong Dal", "Staples & Grains", "Dal", "500 g", 75, 82),
    ("Tata", "Sampann Masoor Dal", "Staples & Grains", "Dal", "500 g", 72, 78),
    ("Organic India", "Quinoa", "Staples & Grains", "Grains", "500 g", 285, 310),
    ("Quaker", "Oats", "Staples & Grains", "Cereals", "1 kg", 185, 199),
    ("Saffola", "Masala Oats", "Staples & Grains", "Cereals", "500 g", 145, 155),
    ("MTR", "Rava Idli Mix", "Staples & Grains", "Ready Mix", "500 g", 75, 82),
    ("Gits", "Gulab Jamun Mix", "Staples & Grains", "Ready Mix", "200 g", 65, 70),
    ("Yippee", "Magic Masala Noodles", "Staples & Grains", "Noodles", "70 g", 14, 14),
    ("Top Ramen", "Curry Noodles", "Staples & Grains", "Noodles", "70 g", 14, 14),
    ("Ching's", "Hakka Noodles", "Staples & Grains", "Noodles", "150 g", 35, 40),
    ("Kikkoman", "Teriyaki Sauce", "Staples & Grains", "Sauces", "200 ml", 185, 199),
    ("Veeba", "Mayonnaise", "Staples & Grains", "Sauces", "250 g", 75, 82),
    ("Kissan", "Tomato Ketchup No Onion Garlic", "Staples & Grains", "Sauces", "500 g", 85, 92),
    ("Tabasco", "Red Pepper Sauce", "Staples & Grains", "Sauces", "60 ml", 195, 210),
    ("Catch", "Black Salt", "Staples & Grains", "Spices", "100 g", 25, 28),
    ("Catch", "Red Chilli Powder", "Staples & Grains", "Spices", "200 g", 65, 70),
    ("Badshah", "Pav Bhaji Masala", "Staples & Grains", "Spices", "100 g", 45, 50),
    ("Keya", "Italian Seasoning", "Staples & Grains", "Spices", "45 g", 55, 60),
    ("Oral-B", "Pro Health Toothpaste", "Personal Care", "Oral Care", "140 g", 95, 105),
    ("Sensodyne", "Repair & Protect", "Personal Care", "Oral Care", "70 g", 145, 155),
    ("Pepsodent", "Germicheck", "Personal Care", "Oral Care", "200 g", 95, 105),
    ("Closeup", "Ever Fresh Gel", "Personal Care", "Oral Care", "150 g", 85, 92),
    ("Lux", "Soft Touch Soap", "Personal Care", "Soap", "125 g", 45, 50),
    ("Lifebuoy", "Total 10 Soap", "Personal Care", "Soap", "125 g", 38, 42),
    ("Pears", "Pure & Gentle", "Personal Care", "Soap", "125 g", 55, 60),
    ("Santoor", "Sandal & Turmeric", "Personal Care", "Soap", "125 g", 42, 45),
    ("Pantene", "Hair Fall Control", "Personal Care", "Hair Care", "180 ml", 225, 245),
    ("Clinic Plus", "Strong & Long", "Personal Care", "Hair Care", "175 ml", 145, 155),
    ("Tresemme", "Keratin Smooth", "Personal Care", "Hair Care", "340 ml", 425, 450),
    ("L'Oreal", "Total Repair Shampoo", "Personal Care", "Hair Care", "360 ml", 395, 425),
    ("Vaseline", "Healthy Bright Lotion", "Personal Care", "Skin Care", "200 ml", 165, 175),
    ("Ponds", "Super Light Gel", "Personal Care", "Skin Care", "73 g", 125, 135),
    ("Garnier", "Micellar Water", "Beauty & Grooming", "Skin Care", "125 ml", 175, 185),
    ("Lakme", "Absolute Perfect Radiance", "Beauty & Grooming", "Skin Care", "50 g", 325, 345),
    ("Maybelline", "Colossal Kajal", "Beauty & Grooming", "Makeup", "0.35 g", 175, 185),
    ("Biotique", "Bio Honey Gel", "Beauty & Grooming", "Skin Care", "190 ml", 195, 210),
    ("Axe", "Dark Temptation Deo", "Beauty & Grooming", "Grooming", "150 ml", 225, 245),
    ("Park Avenue", "Good Morning Deo", "Beauty & Grooming", "Grooming", "150 ml", 195, 210),
    ("Gillette", "Fusion Razor", "Beauty & Grooming", "Grooming", "1 pc", 245, 265),
    ("Veet", "Hair Removal Cream", "Beauty & Grooming", "Grooming", "100 g", 145, 155),
    ("Surf Excel", "Matic Liquid", "Home & Cleaning", "Detergent", "1 L", 225, 245),
    ("Ariel", "Matic Top Load", "Home & Cleaning", "Detergent", "2 kg", 425, 450),
    ("Wheel", "Green Detergent Powder", "Home & Cleaning", "Detergent", "1 kg", 65, 72),
    ("Genteel", "Liquid Detergent", "Home & Cleaning", "Detergent", "1 kg", 185, 199),
    ("Pril", "Dishwash Bar", "Home & Cleaning", "Dishwash", "500 g", 55, 60),
    ("Finish", "Dishwasher Salt", "Home & Cleaning", "Dishwash", "1 kg", 185, 199),
    ("HIT", "Cockroach Spray", "Home & Cleaning", "Pest Control", "400 ml", 185, 199),
    ("Good Knight", "Gold Flash Refill", "Home & Cleaning", "Mosquito", "45 ml", 75, 82),
    ("All Out", "Ultra Refill", "Home & Cleaning", "Mosquito", "45 ml", 72, 78),
    ("Colin", "Glass Cleaner", "Home & Cleaning", "Cleaner", "500 ml", 95, 105),
    ("Cif", "Cream Cleaner", "Home & Cleaning", "Cleaner", "500 ml", 125, 135),
    ("Fresho", "Cucumber", "Fruits & Vegetables", "Vegetables", "500 g", 22, 28),
    ("Fresho", "Lady Finger", "Fruits & Vegetables", "Vegetables", "500 g", 28, 32),
    ("Fresho", "Cauliflower", "Fruits & Vegetables", "Vegetables", "1 pc", 35, 42),
    ("Fresho", "Cabbage", "Fruits & Vegetables", "Vegetables", "1 pc", 28, 32),
    ("Fresho", "Beetroot", "Fruits & Vegetables", "Vegetables", "500 g", 25, 30),
    ("Fresho", "Green Peas", "Fruits & Vegetables", "Vegetables", "500 g", 55, 65),
    ("Fresho", "Sweet Corn", "Fruits & Vegetables", "Vegetables", "2 pcs", 35, 42),
    ("Fresho", "Watermelon", "Fruits & Vegetables", "Fruits", "1 pc", 65, 85),
    ("Fresho", "Papaya", "Fruits & Vegetables", "Fruits", "1 pc", 55, 65),
    ("Fresho", "Grapes Black", "Fruits & Vegetables", "Fruits", "500 g", 85, 99),
    ("Fresho", "Orange Nagpur", "Fruits & Vegetables", "Fruits", "1 kg", 95, 110),
    ("Fresho", "Kiwi", "Fruits & Vegetables", "Fruits", "3 pcs", 95, 110),
    ("Fresho", "Avocado", "Fruits & Vegetables", "Fruits", "1 pc", 125, 145),
    ("Fresho", "Dragon Fruit", "Fruits & Vegetables", "Fruits", "1 pc", 145, 165),
    ("Fresho", "Mushroom Oyster", "Fruits & Vegetables", "Vegetables", "200 g", 65, 75),
    ("Fresho", "Zucchini Green", "Fruits & Vegetables", "Vegetables", "250 g", 55, 65),
    ("Huggies", "Wonder Pants", "Baby Care", "Diapers", "24 pcs", 499, 549),
    ("MamyPoko", "Extra Absorb Pants", "Baby Care", "Diapers", "20 pcs", 425, 475),
    ("Himalaya", "Baby Powder", "Baby Care", "Baby Care", "200 g", 125, 135),
    ("Sebamed", "Baby Cleansing Bar", "Baby Care", "Baby Care", "150 g", 285, 310),
    ("Nestle", "Nan Pro Stage 1", "Baby Care", "Baby Food", "400 g", 645, 695),
    ("Enfamil", "A+ Stage 1", "Baby Care", "Baby Food", "400 g", 725, 775),
    ("Pigeon", "Baby Wipes", "Baby Care", "Baby Care", "80 pcs", 185, 199),
    ("Mee Mee", "Feeding Bottle", "Baby Care", "Baby Care", "250 ml", 225, 245),
    ("Sunfeast", "Bounce Orange", "Bakery", "Biscuits", "100 g", 25, 28),
    ("Sunfeast", "Marie Light", "Bakery", "Biscuits", "250 g", 45, 50),
    ("Britannia", "Cake Gobbles", "Bakery", "Cakes", "65 g", 25, 28),
    ("Britannia", "Fudge It Brownie", "Bakery", "Cakes", "120 g", 45, 50),
    ("Monginis", "Chocolate Muffin", "Bakery", "Cakes", "1 pc", 35, 40),
    ("English Oven", "Multigrain Bread", "Bakery", "Bread", "400 g", 55, 60),
    ("Modern", "Sandwich Bread", "Bakery", "Bread", "400 g", 42, 45),
    ("McCain", "French Fries", "Frozen Food", "Frozen Snacks", "420 g", 135, 145),
    ("McCain", "Aloo Tikki", "Frozen Food", "Frozen Snacks", "400 g", 125, 135),
    ("Yummiez", "Chicken Nuggets", "Frozen Food", "Frozen Snacks", "400 g", 225, 245),
    ("Venky's", "Chicken Sausages", "Frozen Food", "Frozen Snacks", "250 g", 165, 175),
    ("ITC", "Master Chef Sweet Corn", "Frozen Food", "Frozen Veg", "500 g", 85, 95),
    ("Safal", "Mixed Vegetables", "Frozen Food", "Frozen Veg", "500 g", 75, 82),
    ("Pedigree", "Puppy Food", "Pet Care", "Pet Food", "1.2 kg", 345, 375),
    ("Drools", "Adult Dog Food Chicken", "Pet Care", "Pet Food", "1.2 kg", 295, 325),
    ("Whiskas", "Tuna Cat Food", "Pet Care", "Pet Food", "85 g", 45, 50),
    ("Sheba", "Cat Food Fish", "Pet Care", "Pet Food", "70 g", 55, 60),
    ("Drools", "Cat Litter", "Pet Care", "Pet Care", "5 kg", 425, 450),
    ("Himalaya", "Liv.52 Tablets", "Health & Wellness", "Ayurveda", "100 tablets", 145, 155),
    ("Dabur", "Chyawanprash", "Health & Wellness", "Ayurveda", "500 g", 185, 199),
    ("Ensure", "Diabetes Care", "Health & Wellness", "Supplements", "400 g", 725, 775),
    ("Horlicks", "Women's Plus", "Health & Wellness", "Supplements", "400 g", 325, 345),
    ("Bournvita", "500 g Jar", "Health & Wellness", "Supplements", "500 g", 245, 265),
    ("MuscleBlaze", "Whey Protein", "Health & Wellness", "Supplements", "1 kg", 2499, 2699),
    ("Centrum", "Multivitamin", "Health & Wellness", "Supplements", "30 tablets", 425, 450),
    ("Volini", "Pain Relief Spray", "Health & Wellness", "Wellness", "60 g", 145, 155),
    ("Moov", "Pain Relief Cream", "Health & Wellness", "Wellness", "50 g", 125, 135),
    ("Dettol", "Antiseptic Liquid", "Health & Wellness", "Wellness", "550 ml", 225, 245),
    ("Scotch Brite", "Scrub Sponge", "Kitchen Essentials", "Tools", "1 pc", 35, 40),
    ("Scotch Brite", "Steel Scrubber", "Kitchen Essentials", "Tools", "1 pc", 25, 28),
    ("Milton", "Thermosteel Flask", "Kitchen Essentials", "Bottles", "500 ml", 725, 775),
    ("Cello", "Water Bottle", "Kitchen Essentials", "Bottles", "1 L", 185, 199),
    ("Tupperware", "Lunch Box", "Kitchen Essentials", "Storage", "1 pc", 425, 450),
    ("Hawkins", "Pressure Cooker", "Kitchen Essentials", "Cookware", "3 L", 1895, 1995),
    ("Pigeon", "Non-Stick Pan", "Kitchen Essentials", "Cookware", "24 cm", 595, 645),
    ("Philips", "Trimmer", "Electronics", "Grooming", "1 pc", 1295, 1395),
    ("Boat", "Rockerz Earphones", "Electronics", "Audio", "1 pc", 999, 1099),
    ("Portronics", "Power Bank 10000mAh", "Electronics", "Accessories", "1 pc", 899, 999),
    ("Syska", "LED Bulb 12W", "Electronics", "Lighting", "1 pc", 125, 135),
    ("Eveready", "AAA Batteries", "Electronics", "Batteries", "10 pcs", 145, 155),
    ("Panasonic", "AA Batteries", "Electronics", "Batteries", "6 pcs", 95, 105),
    ("Amul", "Dark Chocolate", "Snacks & Munchies", "Chocolate", "150 g", 175, 185),
    ("Toblerone", "Milk Chocolate", "Snacks & Munchies", "Chocolate", "100 g", 195, 210),
    ("Nutella", "Hazelnut Spread", "Staples & Grains", "Spreads", "350 g", 325, 345),
    ("Borges", "Extra Virgin Olive Oil", "Staples & Grains", "Oil", "250 ml", 425, 450),
    ("American Garden", "Peanut Butter", "Staples & Grains", "Spreads", "340 g", 185, 199),
    ("FunFoods", "Sandwich Spread", "Staples & Grains", "Spreads", "275 g", 95, 105),
    ("Del Monte", "Pineapple Slices", "Staples & Grains", "Canned", "450 g", 95, 105),
    ("Green Giant", "Sweet Corn Can", "Staples & Grains", "Canned", "340 g", 75, 82),
    ("Barilla", "Penne Pasta", "Staples & Grains", "Pasta", "500 g", 125, 135),
    ("Bambino", "Vermicelli", "Staples & Grains", "Pasta", "400 g", 45, 50),
    ("Saffola", "Oats Masala", "Staples & Grains", "Cereals", "200 g", 65, 72),
    ("True Elements", "Muesli", "Staples & Grains", "Cereals", "400 g", 245, 265),
    ("Epigamia", "Greek Yogurt", "Dairy & Breakfast", "Curd", "85 g", 45, 50),
    ("Yakult", "Probiotic Drink", "Dairy & Breakfast", "Milk", "65 ml", 15, 15),
    ("Danone", "YoPro Protein Yogurt", "Dairy & Breakfast", "Curd", "150 g", 55, 60),
    ("Go", "Cheese Slices", "Dairy & Breakfast", "Cheese", "200 g", 115, 125),
    ("Milky Mist", "Paneer", "Dairy & Breakfast", "Paneer", "200 g", 85, 95),
    ("Nandini", "Goodlife Milk", "Dairy & Breakfast", "Milk", "500 ml", 28, 30),
    ("Heritage", "Toned Milk", "Dairy & Breakfast", "Milk", "500 ml", 26, 28),
    ("Arokya", "Full Cream Milk", "Dairy & Breakfast", "Milk", "500 ml", 32, 35),
    ("Cremica", "Brown Bread", "Dairy & Breakfast", "Bread", "400 g", 48, 52),
    ("English Oven", "Zero Maida Bread", "Bakery", "Bread", "400 g", 58, 62),
    ("Wingreens", "Hummus Classic", "Staples & Grains", "Dips", "150 g", 125, 135),
    ("Tabasco", "Green Pepper Sauce", "Staples & Grains", "Sauces", "60 ml", 195, 210),
    ("Sriracha", "Hot Chilli Sauce", "Staples & Grains", "Sauces", "200 ml", 145, 155),
    ("Cholula", "Hot Sauce", "Staples & Grains", "Sauces", "150 ml", 325, 345),
    ("Bru", "Green Label Coffee", "Beverages", "Coffee", "200 g", 425, 450),
    ("Starbucks", "Via Instant Coffee", "Beverages", "Coffee", "50 g", 325, 345),
    ("Twinings", "Earl Grey Tea", "Beverages", "Tea", "25 bags", 245, 265),
    ("Organic India", "Tulsi Green Tea", "Beverages", "Tea", "25 bags", 175, 185),
    ("Society", "Tea", "Beverages", "Tea", "250 g", 125, 135),
    ("Lipton", "Yellow Label Tea", "Beverages", "Tea", "250 g", 135, 145),
    ("Bacardi", "Mixer Tonic Water", "Beverages", "Mixers", "250 ml", 45, 50),
    ("Schweppes", "Ginger Ale", "Beverages", "Mixers", "250 ml", 45, 50),
    ("Bisleri", "Soda", "Beverages", "Water", "750 ml", 25, 28),
    ("Paper Boat", "Jaljeera", "Beverages", "Juice", "250 ml", 25, 28),
    ("Real", "Coconut Water", "Beverages", "Juice", "1 L", 95, 105),
    ("Raw", "Coconut Water", "Beverages", "Juice", "200 ml", 45, 50),
    ("Himalayan", "Natural Mineral Water", "Beverages", "Water", "1 L", 55, 60),
    ("Evian", "Natural Spring Water", "Beverages", "Water", "1 L", 125, 135),
    ("Tata", "Copper Water Bottle", "Kitchen Essentials", "Bottles", "1 L", 425, 450),
    ("Milton", "Copper Bottle", "Kitchen Essentials", "Bottles", "900 ml", 545, 575),
    ("Cello", "Glass Tumbler Set", "Kitchen Essentials", "Serveware", "6 pcs", 325, 345),
    ("Borosil", "Microwave Bowl Set", "Kitchen Essentials", "Serveware", "3 pcs", 425, 450),
    ("Prestige", "Gas Lighter", "Kitchen Essentials", "Tools", "1 pc", 125, 135),
    ("Pigeon", "Gas Stove 2 Burner", "Kitchen Essentials", "Cookware", "1 pc", 2495, 2695),
    ("Bajaj", "LED Emergency Light", "Electronics", "Lighting", "1 pc", 895, 995),
    ("Wipro", "LED Batten 20W", "Electronics", "Lighting", "1 pc", 245, 265),
    ("Mi", "Smart Bulb", "Electronics", "Lighting", "1 pc", 799, 899),
    ("Amazon Basics", "USB Cable", "Electronics", "Accessories", "1 m", 299, 349),
    ("Logitech", "Wireless Mouse", "Electronics", "Accessories", "1 pc", 695, 795),
    ("JBL", "Go Speaker", "Electronics", "Audio", "1 pc", 2495, 2695),
    ("boAt", "Airdopes", "Electronics", "Audio", "1 pc", 1299, 1499),
]
